### ISSUE TITLE
some errors for the latest server MaNGOS One/0.12.2 (* * Revision 1924 - *)

### ISSUE THREAD

**Issue by apo126** [mangosArchives/databaseOneRel18#1]
1)
ERROR:Creature (Entry: 10760) has invalid maxlevel, set to minlevel
ERROR:Creature (Entry: 14302) has invalid maxlevel, set to minlevel
ERROR:Creature (Entry: 15936) has invalid maxlevel, set to minlevel
ERROR:Creature (Entry: 19799) has invalid maxlevel, set to minlevel
ERROR:Creature (Entry: 19821) has invalid maxlevel, set to minlevel
ERROR:Creature (Entry: 21860) has invalid maxlevel, set to minlevel
2)
ERROR:Spell (id: 33824) have SPELL_EFFECT_QUEST_COMPLETE for quest 10162 , but quest does not have SpecialFlags QUEST_SPECIAL_FLAG_EXPLORATION_OR_EVENT (2) set. Quest SpecialFlags should be corrected to enable this objective.

**Comment by billy1arm** [comment]
these have been cleaned up in Rel20
