### ISSUE TITLE
Spectral Rift Object

### ISSUE THREAD

**Issue by Mibu86** [mangosArchives/databaseOneRel18#3]
187055  10  1327    Spectral Rift (temp)            0   0   1   57  0   0   0   0   0   1000    0   0   0   44811   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

Correct data

**Comment by billy1arm** [comment]
@Mibu86 - do you have any source / links to back this up ?

**Comment by Mibu86** [comment]
facepalm... muahaha... it's been 1 year...yea the data is correct...for the old database..if there wasn't any column changes ..it's still right..
Well you can check the data yourself..there isnt much difference with the incorrect one you have just compare them...and you will see onlly the spell is modified with the correct one from wut i remember.
i belive http://www.wowhead.com/spell=44811/spectral-realm
yours have the rong spell or used to have..haven't checked you're db in quite some time..but fixing the portal wont fix the teleport...some core issue again i remember.

**Comment by Mibu86** [comment]
You can still fix it...with a script...that would override that broken core teleport..i would use .lua but in ure case c++.. try a script like..
Player is affected by spell 44811(bla bla just a pinpoint) use on player .go creature "Sathrovarr the Corruptor"  issue solved... or even better... : 
"Player uses Spectral rift (object) -ll-  ....
 .go creature works perfectly.. and remove the spell from it ...
